chore(deps): adds setuptools as a explicit dep
... otherwise we get the following error (more often in python 3.12),
perhaps due to setuptools being removed from distros?:

```text
Traceback (most recent call last):
  File "/var/www/mydir/virtualenvs/dev/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```